// src/features/cv/components/header/cv-header.tsx
import { FC } from 'react';
import { CvHeaderProps } from '@/features/cv/components/header/types';
import './cv-header.scss';
import Image from 'next/image';

export const CvHeader: FC<CvHeaderProps> = (props: CvHeaderProps) => {
  return (
    <div className="header">
      <div className="header__info">
        <h2 className="header__title">{props.title}</h2>
        <h5 className="header__job">{props.job}</h5>
      </div>
      <Image
        className="header__photo"
        src={props.photoUrl}
        alt="photo"
        loading="lazy"
        width={50}
        height={50}
      />
    </div>
  );
};

// apps/frontend/src/app/features/cv/components/cv-header/cv-header.component.ts
import { Component, Input } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { DEFAULT_PLACEHOLDER } from '@packages/common';

@Component({
  selector: 'app-cv-header',
  standalone: true,
  imports: [NgOptimizedImage],
  templateUrl: './cv-header.component.html',
  styleUrl: './cv-header.component.scss',
})
export class CvHeaderComponent {
  @Input() title: string = DEFAULT_PLACEHOLDER;
  @Input() job: string = DEFAULT_PLACEHOLDER;
  @Input() photoUrl: string = './assets/photo.webp';
}

<header class="cv-header flex flex-row justify-between items-center">
  <div class="cv-header__info">
    <h2 class="my-1 text-3xl font-medium uppercase">{{ title }}</h2>
    <h5 class="cv-header__job my-1 text-2xl font-medium">{{ job }}</h5>
  </div>
  <img
    class="cv-header__photo rounded-full bg-center bg-no-repeat"
    [ngSrc]="photoUrl"
    alt="photo"
    loading="lazy"
    height="10"
    width="10"
  />
</header>
